DELETE  http://localhost:3001/api/persons/609155b08fa38f2c3be1ceacd
###

GET http://localhost:3001/api/persons/609155b08fa38f2c3be1cead

###
POST http://localhost:3001/api/persons/ HTTP/1.1
Content-Type: application/json

{
  "name": "Luong Tuan Anh",
  "number": "0312488321"
}

###
PUT http://localhost:3001/api/persons/609155b08fa38f2c3be1cead
Content-Type: application/json

{
  "name": "Luong Tuan Ah",
  "number": ""
}